# Install the required packages
install.packages("librarian")
librarian::shelf(
  dplyr,
  readr,
  expss,
  janitor,
  tidyverse,
  rstudioapi,
  stringr,
  reshape2,
  readxl,
  cowplot,
  ggpubr,
  Rmisc,
  DescTools,
  see,
  hrbrthemes,
  bibliometrix,
  gginnards,
  update_all = FALSE
)

##Setup working Directory
setwd(dirname(getActiveDocumentContext()$path))





# USING BIBLIOMETRIX 

# Data loading and conversion
data_bib <- convert2df(file = "Data/study_records/full_rec_bib.txt", dbsource = "wos", format = "plaintext")






# Main bibliometric analysis
results <- biblioAnalysis(data_bib, sep = ";")



options(width=100)
bib_summary <- summary(object = results, k = 10, pause = FALSE)

# plot(x = results, k = 10, pause = FALSE)




# YEARS
#generate yearly count data from the raw data generated by 'biblioAnalysis' package
years <- results$Years %>%
  plyr::count() %>% 
  na.omit() %>%
  dplyr::rename("year" = 1,
                "count" = 2) %>%
  as_tibble()

  


years[,"cum_count"] <- cumsum(years$count)

scale = 10

fig_years <- 
ggplot(data = years,
       aes(x = year)) +
  geom_bar(aes(y = count, fill="cum_count"),
            stat = "identity",
            width = 0.85,
            # color = NA,
            # fill = "#A6D1C6",
           alpha = 0.5
            ) +
  # geom_text(aes(label = count, y = count), size = 2.75, vjust=-1.5)+
  geom_line(aes(y = cum_count/4, colour="cum_count"),
            # color = "#69b3a2",
            # color = "#8c510a",
            size = 0.8,
            # linetype = "dashed"
            )+
  theme_pubr()+
  scale_color_manual(values = c("#69b3a2"),
                     label = "Cumulative publications",
                      name = "")+
  scale_fill_manual(values = c("#A6D1C6"),
                    label = "Annual publications",
                    name = "")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 200, by = 50),
                     limits = c(0, 200),
    sec.axis = sec_axis(trans = ~.*4, name = "Cumulative publications")
  )+
  labs(
        x = "Year", 
       y = "Annual publications")+
  scale_x_continuous(breaks = seq(1980, 2022, by =5))+
  theme(#panel.grid.major.y = element_line(color = "#DAE1E7"),
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )

fig_years







# COUNTRIES: COUNT
#generate country count data from the raw data generated by 'biblioAnalysis' package
country_count <- results$Countries %>%
  as_tibble() %>%
  dplyr::rename("country" = 1,
                "count" = 2)%>%
  mutate(perc = paste0(round(count/sum(count)*100,2),"%")) #calculate percentage of papers 



country_count




fig_country <- 
  country_count %>%
  slice(c(1:10))%>%
  mutate(country=factor(country)) %>%
  ggplot(aes(x= reorder(country, count), y=count) ) +
  geom_bar(stat="identity", fill="#A6D1C6") +
  geom_text(aes(label = perc), size = 3.75, y= 7)+
  geom_text(aes(label = count), size = 3.75, hjust = -0.35)+
  scale_y_continuous(limits = c(0,150),
                     expand = c(0, 0)) +
  coord_flip() +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(x = "", y = "Count" )

fig_country 







#  WoS Categories
wos_cat <- read_delim("Data/study_records/wos_cat.txt", delim = "\t", 
                      escape_double = FALSE, trim_ws = TRUE)%>%
  as.data.frame()%>%
  dplyr::rename("cat" = 1, 
                "count" = 2)%>%
  mutate(perc = paste0(round(count/686*100,2),"%"))


wos_cat


fig_wos_cat <- 
  wos_cat %>%
  slice(c(1:15))%>%
  mutate(cat=factor(cat)) %>%
  ggplot(aes(x= reorder(cat, count), y=count) ) +
  geom_bar(stat="identity", fill="#A6D1C6") +
  geom_text(aes(label = perc), size = 3, y= 8)+
  coord_flip() +
  scale_y_continuous(
    breaks = seq(0,180, by = 40),
    limits = c(0, 180),
    expand = c(0, 0)) +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(x = "", y = "Count" )

fig_wos_cat 
  






# TOPIC TRENDS
# Generating synonym/thesaurus data for keyword trend analysis
synonym <- c("lettuce; lactuca sativa; lactuca sativa l.; lactuca-sativa l.; l.",
             "led; leds; light emitting-diodes; light-emitting-diodes; led light; light-emitting diodes; emitting-diodes led; light-emitting diode",
             "hydroponics; hydroponic; hydro-ponic",
             "artificial intelligence; ai; machine learning",
             "vertical farms; vertical farming;  vertical farm; vf; vertical-farming; vetical-farms",
             "cea; controlled environment agriculture (cea); controlled environment agriculture; controlled environment",
             "plant factory; pfals;pfal; plant factories",
             "secondary metabolites; antioxidant"
)



#Generate topic trend using author keyword (DE) 
trend <- fieldByYear(data_bib, field = "DE", min.freq = 5, n.items =5, graph = F,
                     synonyms = synonym)
x <- trend$graph # graph produced by default
x


ff <- trend$df_graph%>%as_tibble()

data_trend_graph <- ff#%>%slice(-c(3, 7:8, 14:17, 20 ))


trend_plot <- 
  ggplot(data = data_trend_graph,
         aes(x = item,
             y = year_med)) +
  geom_linerange(aes(ymin = year_q1, ymax = year_q3),
                 size = 0.95,  color = "#69b3a2") +
  geom_point(aes(size = freq), color = "#69b3a2", alpha = 0.7) +
  scale_size(range = c(2, 7), name="Term frequency")+
  coord_flip() + 
  theme_pubr()+
  theme(panel.grid.major.y = element_line(color = "#DAE1E7", size = 0.2),
        axis.line.y = element_blank())+
  labs(x = "Author keywords",
       y = "Year")+
  scale_y_continuous(
    breaks = seq(2010,2025, by = 5),
    limits = c(2010, 2022)) 
  
trend_plot









#_________________________
#_________________________


# AUTHOR KEYWORDS
# Creating a function to subst master dataset to the specified authors and generate bibliometrics
author_summary <-
  function(x) {
    data_bib %>%
      filter(grepl(x, AU)) %>%
      biblioAnalysis(sep = ";") %>%
      summary(k = 10, pause = FALSE)
    
  }


author_summary("OH MM")
author_summary("SON JE")
author_summary("LIU WK")
author_summary("LU N")
author_summary("TAKAGAKI M")
author_summary("LIU HC")
author_summary("GOTO E")
author_summary("CHUN C")
author_summary("YANG QC")
author_summary("JEONG BR")
author_summary("MARCELIS LFM")
author_summary("SONG SW")
author_summary("SON KH")
author_summary("KOZAI T")
author_summary("STANGHELLINI C")
author_summary("NIU G")
author_summary("YAMORI W")
author_summary("GRAAMANS L")
author_summary("VAN DEN DOBBELSTEEN A")
author_summary("WHEELER RM")
author_summary("ORSINI F")







#_____________________________________________________________________________

# CROP COUNT
crop_data <- read_excel("Data/crop/crop_data_extraction.xlsx", sheet = "savedrecs")%>%
  dplyr::select(c(1, 10, 11))%>%
  dplyr::mutate(
    crop = as.factor(crop),
    crop_category = as.factor(crop_category),
    study_id = as.factor(study_id)
  )


crop_data <- separate_rows(crop_data, crop, sep = ",")# Separating comma separated multiple crops per study into individual column



# Create a dataset with crop counts
crop_count <- count(crop_data$crop)%>%
  as_tibble()%>%
  dplyr::mutate(
  freq = as.numeric(freq),
  x = as.factor(x))%>%
  dplyr::rename(crop = x,
         studies = freq)%>%
  arrange(-studies)

head(crop_count)



# Top 10 crops studied
fig_crop_studies <- 
  crop_count %>%
  slice(c(1:10))%>%
  ggplot(aes(x = reorder(crop, studies), y = studies)) +
  geom_bar(stat = "identity",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip()+
  geom_text(aes(label = studies), size = 3.75, hjust = -0.45)+
  scale_y_continuous(
    breaks = seq(0,125, by = 25),
    limits = c(0, 135),
    expand = c(0, 0)) +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(
    y = "No. of publications",
    x = "Crop"
  )

fig_crop_studies 











# Create a dataset with category counts
crop_cat <- count(crop_data$crop_category)%>%
  as_tibble()%>%
  dplyr::mutate(
    freq = as.numeric(freq),
    x = as.factor(x))%>%
  dplyr::rename(cat = x,
                studies = freq)%>%
  arrange(-studies)

head(crop_cat)


# Top 10 crop categories studied
crop_cat_studies <- 
  crop_cat %>%
  slice(c(1:10))%>%
  ggplot(aes(x = reorder(cat, studies), y = studies)) +
  geom_bar(stat = "summary",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip() +
  geom_text(aes(label = studies), size = 3.75, hjust = -0.4)+
  scale_y_continuous(breaks = seq(0, 175, by = 25),
                     limits = c(0, 200),
                     expand = c(0, 0)) +
  theme_pubr() +
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position = "none"
  )+
  labs(
    y = "No. of publications",
    x = "Crop category"
  )

crop_cat_studies  
  



# Top 10 crop categories with most crops

crop_cat_species <- crop_data%>%
  filter(duplicated(crop) == FALSE)%>%
  dplyr::count(crop_category)%>%
  as_tibble()%>%
  dplyr::mutate(
    n = as.numeric(n),
    crop_category = as.factor(crop_category))%>%
  dplyr::rename(
                species = n)%>%
  arrange(-species)
  






crop_cat_crop <- 
  crop_cat_species%>%
  ggplot(aes(x = reorder(crop_category, species), y = species)) +
  geom_bar(stat = "summary",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip() +
  geom_text(aes(label = species), size = 3.75, hjust = -0.4)+
  scale_y_continuous(breaks = seq(0, 25, by = 5),
                     limits = c(0, 26),
                     expand = c(0, 0)) +
  theme_pubr() +
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position = "none"
  )+
  labs(
    y = "No. of crop species",
    x = "Crop category"
  )

crop_cat_crop 
  


















#_____________________________________________________________________________
#_____________________________________________________________________________

# YEARS
ggsave("Plots/years.pdf", fig_years,  width=7.2, height=4.5)



#COUNTRIES
ggsave("Plots/country.pdf", fig_country,  width=7.2, height=4.5)


#CATEGORIES
ggsave("Plots/wos_cat.pdf", fig_wos_cat,  width=8, height=5)


#TREND
ggsave("Plots/trend.pdf", trend_plot,  width=8.2, height=5.5)

# #THEME MAP
# ggsave("Plots/theme_map.pdf", theme_map_fig, width=8.2, height=5)





# CROPS
crop_col <- ggarrange(fig_crop_studies, crop_cat_studies, crop_cat_crop,
                       nrow = 1, ncol = 3,
                       labels = "auto",
                       align = "hv")

crop_col

ggsave("Plots/crops.pdf", crop_col,  width=17, height=4)




