# Install the required packages
install.packages("librarian")
librarian::shelf(
  dplyr,
  readr,
  expss,
  janitor,
  tidyverse,
  rstudioapi,
  stringr,
  reshape2,
  readxl,
  cowplot,
  ggpubr,
  Rmisc,
  DescTools,
  see,
  hrbrthemes,
  bibliometrix,
  gginnards,
  update_all = FALSE
)

##Setup working Directory
setwd(dirname(getActiveDocumentContext()$path))





# USING BIBLIOMETRIX 

# Data loading and conversion
data_bib <- convert2df(file = "Data/study_records/full_rec_bib.txt", dbsource = "wos", format = "plaintext")






# Main bibliometric analysis
results <- biblioAnalysis(data_bib, sep = ";")



options(width=100)
bib_summary <- summary(object = results, k = 10, pause = FALSE)

# plot(x = results, k = 10, pause = FALSE)




# YEARS
#generate yearly count data from the raw data generated by 'biblioAnalysis' package
years <- results$Years %>%
  plyr::count() %>% 
  na.omit() %>%
  dplyr::rename("year" = 1,
                "count" = 2) %>%
  as_tibble()

  


years[,"cum_count"] <- cumsum(years$count)

scale = 10

fig_years <- 
ggplot(data = years,
       aes(x = year)) +
  geom_bar(aes(y = count, fill="cum_count"),
            stat = "identity",
            width = 0.85,
            # color = NA,
            # fill = "#A6D1C6",
           alpha = 0.5
            ) +
  # geom_text(aes(label = count, y = count), size = 2.75, vjust=-1.5)+
  geom_line(aes(y = cum_count/4, colour="cum_count"),
            # color = "#69b3a2",
            # color = "#8c510a",
            size = 0.8,
            # linetype = "dashed"
            )+
  theme_pubr()+
  scale_color_manual(values = c("#69b3a2"),
                     label = "Cumulative publications",
                      name = "")+
  scale_fill_manual(values = c("#A6D1C6"),
                    label = "Annual publications",
                    name = "")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 200, by = 50),
                     limits = c(0, 200),
    sec.axis = sec_axis(trans = ~.*4, name = "Cumulative publications")
  )+
  labs(
        x = "Year", 
       y = "Annual publications")+
  scale_x_continuous(breaks = seq(1980, 2022, by =5))+
  theme(#panel.grid.major.y = element_line(color = "#DAE1E7"),
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )

fig_years







# COUNTRIES: COUNT
#generate country count data from the raw data generated by 'biblioAnalysis' package
country_count <- results$Countries %>%
  as_tibble() %>%
  dplyr::rename("country" = 1,
                "count" = 2)%>%
  mutate(perc = paste0(round(count/sum(count)*100,2),"%")) #calculate percentage of papers 



country_count




fig_country <- 
  country_count %>%
  slice(c(1:10))%>%
  mutate(country=factor(country)) %>%
  ggplot(aes(x= reorder(country, count), y=count) ) +
  geom_bar(stat="identity", fill="#A6D1C6") +
  geom_text(aes(label = perc), size = 3.75, y= 7)+
  geom_text(aes(label = count), size = 3.75, hjust = -0.35)+
  scale_y_continuous(limits = c(0,150),
                     expand = c(0, 0)) +
  coord_flip() +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(x = "", y = "Count" )

fig_country 







#  WoS Categories
wos_cat <- read_delim("Data/study_records/wos_cat.txt", delim = "\t", 
                      escape_double = FALSE, trim_ws = TRUE)%>%
  as.data.frame()%>%
  dplyr::rename("cat" = 1, 
                "count" = 2)%>%
  mutate(perc = paste0(round(count/686*100,2),"%"))


wos_cat


fig_wos_cat <- 
  wos_cat %>%
  slice(c(1:15))%>%
  mutate(cat=factor(cat)) %>%
  ggplot(aes(x= reorder(cat, count), y=count) ) +
  geom_bar(stat="identity", fill="#A6D1C6") +
  geom_text(aes(label = perc), size = 3, y= 8)+
  coord_flip() +
  scale_y_continuous(
    breaks = seq(0,180, by = 40),
    limits = c(0, 180),
    expand = c(0, 0)) +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(x = "", y = "Count" )

fig_wos_cat 
  






# TOPIC TRENDS
# Generating synonym/thesaurus data for keyword trend analysis
synonym <- c("lettuce; lactuca sativa; lactuca sativa l.; lactuca-sativa l.; l.",
             "led; leds; light emitting-diodes; light-emitting-diodes; led light; light-emitting diodes; emitting-diodes led; light-emitting diode",
             "hydroponics; hydroponic; hydro-ponic",
             "artificial intelligence; ai; machine learning",
             "vertical farms; vertical farming;  vertical farm; vf; vertical-farming; vetical-farms",
             "cea; controlled environment agriculture (cea); controlled environment agriculture; controlled environment",
             "plant factory; pfals;pfal; plant factories",
             "secondary metabolites; antioxidant"
)



#Generate topic trend using author keyword (DE) 
trend <- fieldByYear(data_bib, field = "DE", min.freq = 5, n.items =5, graph = F,
                     synonyms = synonym)
x <- trend$graph # graph produced by default
x


ff <- trend$df_graph%>%as_tibble()

data_trend_graph <- ff#%>%slice(-c(3, 7:8, 14:17, 20 ))


trend_plot <- 
  ggplot(data = data_trend_graph,
         aes(x = item,
             y = year_med)) +
  geom_linerange(aes(ymin = year_q1, ymax = year_q3),
                 size = 0.95,  color = "#69b3a2") +
  geom_point(aes(size = freq), color = "#69b3a2", alpha = 0.7) +
  scale_size(range = c(2, 7), name="Term frequency")+
  coord_flip() + 
  theme_pubr()+
  theme(panel.grid.major.y = element_line(color = "#DAE1E7", size = 0.2),
        axis.line.y = element_blank())+
  labs(x = "Author keywords",
       y = "Year")+
  scale_y_continuous(
    breaks = seq(2010,2025, by = 5),
    limits = c(2010, 2022)) 
  
trend_plot









#_________________________
#_________________________


# AUTHOR KEYWORDS
# Creating a function to subst master dataset to the specified authors and generate bibliometrics
author_summary <-
  function(x) {
    data_bib %>%
      filter(grepl(x, AU)) %>%
      biblioAnalysis(sep = ";") %>%
      summary(k = 10, pause = FALSE)
    
  }


author_summary("OH MM")
author_summary("SON JE")
author_summary("LIU WK")
author_summary("LU N")
author_summary("TAKAGAKI M")
author_summary("LIU HC")
author_summary("GOTO E")
author_summary("CHUN C")
author_summary("YANG QC")
author_summary("JEONG BR")
author_summary("MARCELIS LFM")
author_summary("SONG SW")
author_summary("SON KH")
author_summary("KOZAI T")
author_summary("STANGHELLINI C")
author_summary("NIU G")
author_summary("YAMORI W")
author_summary("GRAAMANS L")
author_summary("VAN DEN DOBBELSTEEN A")
author_summary("WHEELER RM")
author_summary("ORSINI F")







#_____________________________________________________________________________

# CROP COUNT
crop_count <- read_excel("Data/crop_data/crop_count.xlsx")%>%
  dplyr::mutate(
    crop = as.factor(crop),
    category = as.factor(category),
    super_cat = as.factor(super_cat)
  )

# Top 10 crops studied
fig_crop_studies <- 
  crop_count %>%
  dplyr::slice(c(1:10)) %>%
  ggplot(aes(x = reorder(crop, studies), y = studies)) +
  geom_bar(stat = "summary",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip()+
  geom_text(aes(label = studies), size = 3.75, hjust = -0.45)+
  scale_y_continuous(
    breaks = seq(0,125, by = 25),
    limits = c(0, 130),
    expand = c(0, 0)) +
  theme_pubr()+
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position="none"
  ) +
  labs(
    y = "No. of publications",
    x = "Crop"
  )

fig_crop_studies 





# Top 10 crop categories studied
crop_cat_studies <- 
  summarySE(data = crop_count,
          measurevar = "studies",
          groupvars = "category") %>%
  mutate(studies = N * studies) %>%
  select(c(1, 3)) %>%
  ggplot(aes(x = reorder(category, studies), y = studies)) +
  geom_bar(stat = "summary",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip() +
  geom_text(aes(label = studies), size = 3.75, hjust = -0.4)+
  scale_y_continuous(breaks = seq(0, 175, by = 25),
                     limits = c(0, 190),
                     expand = c(0, 0)) +
  theme_pubr() +
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position = "none"
  )+
  labs(
    y = "No. of publications",
    x = "Crop category"
  )

crop_cat_studies  
  



# Top 10 crop categories with most crops
crop_cat_crop <- 
  summarySE(data = crop_count,
          measurevar = "studies",
          groupvars = "category") %>%
  select(c(1, 2)) %>%
  ggplot(aes(x = reorder(category, N), y = N)) +
  geom_bar(stat = "summary",
           color = NA,
           fill = "#A6D1C6") +
  coord_flip() +
  geom_text(aes(label = N), size = 3.75, hjust = -0.4)+
  scale_y_continuous(breaks = seq(0, 25, by = 5),
                     limits = c(0, 26),
                     expand = c(0, 0)) +
  theme_pubr() +
  theme(
    axis.line.y = element_blank(),
    panel.grid.major.x = element_line(color = "#DAE1E7", size = 0.25),
    panel.grid.minor.x = element_line(color = "#DAE1E7", size = 0.1),
    legend.position = "none"
  )+
  labs(
    y = "No. of crop species",
    x = "Crop category"
  )

crop_cat_crop 
  



library("ggrepel")


# Crop distributions
crop_dist_supercat <-   
  summarySE(data = crop_count,
          measurevar = "studies",
          groupvars = "super_cat") %>%
  mutate(studies = N * studies)%>%
  select(c(1,3))%>%
  mutate(prop = studies/sum(studies))%>%
  mutate(perc = paste0(round(prop*100,2),"%"))%>%
  mutate(xvar = "xvar")%>%
  ggplot( aes(x = xvar, y = prop, fill = super_cat)) +
  geom_col(width =0.5) +
  # geom_text(aes(label = paste0(perc)),
  #           position = position_stack(vjust = 0.5)) +
  # geom_text_repel(aes(label = paste0(perc)), position = position_stack(vjust = 0.5),vjust = 5, hjust = 5)+
  scale_fill_brewer(palette = "Set2") +
  theme_void() +
  coord_flip()

crop_dist_supercat
  



crop_dist_food <- 
  crop_count%>%
  filter(str_detect(super_cat, "Food"))%>%
  summarySE(
          measurevar = "studies",
          groupvars = "category") %>%
  mutate(studies = N * studies)%>%
  select(c(1,3))%>%
  mutate(prop = studies/sum(studies))%>%
  mutate(perc = paste0(round(prop*100,2),"%"))%>%
  mutate(xvar = "xvar")%>%
  ggplot( aes(x = xvar, y = prop, fill = category)) +
  geom_col(width =0.5) +
  # geom_text(aes(label = paste0(perc)),
  #           position = position_stack(vjust = 0.5)) +
  geom_text_repel(aes(label = paste0(perc)),  position = position_stack(vjust = 0.5), direction = "y")+
  scale_fill_brewer(palette = "Set3") +
  theme_void() +
  coord_flip()

crop_dist_food  
  







# theme_map <- thematicMap(data_bib, field = "DE", n = 250, minfreq =8,
#             stemming = F, size = 0.1, n.labels=3, repel = T, community.repulsion = 0.1,
#             remove.terms = c("controlled environment agriculture (cea)", "rosmarinic acid"))
# 
# theme_map_fig <- theme_map$map
# theme_map_fig 









#_____________________________________________________________________________
#_____________________________________________________________________________

# YEARS
ggsave("Plots/years.pdf", fig_years,  width=7.2, height=4.5)



#COUNTRIES
ggsave("Plots/country.pdf", fig_country,  width=7.2, height=4.5)


#CATEGORIES
ggsave("Plots/wos_cat.pdf", fig_wos_cat,  width=8, height=5)


#TREND
ggsave("Plots/trend.pdf", trend_plot,  width=8.2, height=5.5)

# #THEME MAP
# ggsave("Plots/theme_map.pdf", theme_map_fig, width=8.2, height=5)





# CROPS
crop_col1 <- ggarrange(crop_dist_supercat,
                       crop_dist_food,
                       nrow = 2, ncol = 1,
                       labels = c("d", "e"),
                       align = "hv")


crop_col2 <- ggarrange(fig_crop_studies, crop_cat_studies, #crop_cat_crop, crop_col1,
                      nrow = 1, ncol = 2,
                      labels = c("a", "b"),
                      align = "hv")

crop_col2

# ggsave("Plots/crop2.pdf", crop_col2,  width=10, height=7)




crop_col3 <- ggarrange(crop_cat_crop, crop_col1,
                       nrow = 1, ncol = 2,
                       labels = c("c", " "),
                       align = "h")



fig_crop <- 
  ggarrange(crop_col2, crop_col3,
          nrow = 2, ncol = 1,
          labels = NULL,
          align = "hv")
fig_crop

ggsave("Plots/crop3.pdf", fig_crop,  width=14.75, height=10)






# # #Research Area
# ra <- read_xls("Data/full_rec.xls", sheet= "savedrecs")%>%
#   select(c(9,64))%>%
#   # as.data.frame()%>%
#   dplyr::rename("title" = 1,
#                 "areas" = 2)#%>%
#   separate(col = "areas", sep = ";", into = c("a", "b", "c","d","e"))
# 
# 
#   
#   
#   
#   
#   
# 
# ggvenn(
#   x,
#   columns = c("a", "b"),
#   # fill_color = c("#0073C2FF", "#EFC000FF"),
#   stroke_size = 0.5, set_name_size = 5
# )
# 
# 
# 
# x <- list(
#  a = Life_sciences,
#  b = Phy_sciences
# )
# 
# 
# str(x)
# 
# 
# 
# 
# Life_sciences <-
#   ra %>%
#   filter(grepl(c("Agriculture", "Anthropology",
#                  "Biochemistry & Molecular Biology",
#                  "Biotechnology & Applied Microbiology",
#                  "Life Sciences & Biomedicine",
#                  "Environmental Sciences & Ecology",
#                  "Food Science & Technology",
#                  "Mathematics",
#                  "Microbiology", 
#                  "Plant Sciences",
#                  "Zoology"), areas)) %>%
#   select(1)%>%as.character()
# 
# 
# Phy_sciences <-
#   ra %>%
#   filter(grepl(c("Chemistry",
#                  "Mathematics",
#                  "Physics", 
#                  "Water Resources",
#                  "Astronomy & Astrophysics"), areas)) %>%
#   select(1)%>%as.character()
# 
# 
# 
# 
# 
